[package]
name = "rusty_terrain"
version = "0.1.0"
authors = ["Bob Urberger <burberger@gmail.com>"]

[dependencies]
ndarray = "0.9.1"
rand = "0.3.15"
image = "0.13.0"
kiss3d = "0.9.0"
nalgebra = "0.12.3"
